### ISSUE TITLE
Feature request: Drag and drop elements

### ISSUE THREAD

**Issue by idoo** [unmade/gantt-chart#1]
Can you add this feature to lib, please?

**Comment by unmade** [comment]
Попробую, как будет время.

**Comment by idoo** [comment]
@unmade спасибо, буду ждать :)

**Comment by unmade** [comment]
Добавил. Обновил [демо](http://codepen.io/fdooch/pen/reyWeO).

**Comment by unmade** [comment]
@idoo Я могу закрывать?

**Comment by idoo** [comment]
@unmade да, спасибо!
